# Generated by Django 6.0.1 on 2026-01-13 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_hy', models.CharField(max_length=200, null=True)),
                ('name_ru', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_hy', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(default='📄', help_text='Emoji or icon code', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Application Type',
                'verbose_name_plural': 'Application Types',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_content', models.TextField(help_text='Template with placeholders like {{field_name}}')),
                ('template_format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX')], default='pdf', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='applications.applicationtype')),
            ],
            options={
                'verbose_name': 'Application Template',
                'verbose_name_plural': 'Application Templates',
            },
        ),
        migrations.CreateModel(
            name='ApplicationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Internal field name (e.g., full_name)', max_length=100)),
                ('label', models.CharField(help_text='Display label (e.g., Full Name)', max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('email', 'Email'), ('date', 'Date'), ('number', 'Number'), ('select', 'Dropdown'), ('checkbox', 'Checkbox')], default='text', max_length=20)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('help_text', models.TextField(blank=True, help_text='Help text shown below the field')),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('options', models.TextField(blank=True, help_text='For select/checkbox: comma-separated options')),
                ('validation_regex', models.CharField(blank=True, help_text='Optional regex pattern for validation', max_length=200)),
                ('application_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='applications.applicationtype')),
            ],
            options={
                'ordering': ['order', 'field_name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_data', models.JSONField(help_text='Stored form data as JSON')),
                ('generated_file', models.FileField(blank=True, null=True, upload_to='applications/generated/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.applicationtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
