# Generated by Django 6.0.1 on 2026-01-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='content_hy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_hy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_hy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='button_text_en',
            field=models.CharField(default='Learn More', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='button_text_hy',
            field=models.CharField(default='Learn More', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='button_text_ru',
            field=models.CharField(default='Learn More', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='description_hy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='title_hy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_hy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_hy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_hy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
