# Generated by Django 6.0.1 on 2026-01-11 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('case_type', models.CharField(choices=[('criminal', 'Criminal Case'), ('civil', 'Civil Case'), ('administrative', 'Administrative Case')], max_length=20)),
                ('description', models.TextField()),
                ('scenario', models.TextField(help_text='Case scenario and facts')),
                ('evidence', models.TextField(help_text='Available evidence')),
                ('legal_documents', models.FileField(blank=True, null=True, upload_to='case_documents/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hypothesis', models.TextField(help_text='Investigative hypothesis')),
                ('legal_qualification', models.TextField(help_text='Legal qualification')),
                ('conclusion', models.TextField(help_text='Legal conclusion')),
                ('is_evaluated', models.BooleanField(default=False)),
                ('evaluation', models.TextField(blank=True, help_text='Admin evaluation')),
                ('score', models.IntegerField(default=0, help_text='Score out of 100')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_analyses', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='cases.legalcase')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('case', 'user')},
            },
        ),
    ]
