# Generated by Django 6.0.1 on 2026-01-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalcase',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='description_hy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='evidence_en',
            field=models.TextField(help_text='Available evidence', null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='evidence_hy',
            field=models.TextField(help_text='Available evidence', null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='evidence_ru',
            field=models.TextField(help_text='Available evidence', null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='scenario_en',
            field=models.TextField(help_text='Case scenario and facts', null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='scenario_hy',
            field=models.TextField(help_text='Case scenario and facts', null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='scenario_ru',
            field=models.TextField(help_text='Case scenario and facts', null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='title_hy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
