# Generated by Django 6.0.1 on 2026-01-11 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiplayerGameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(help_text='Unique room code for joining', max_length=8, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('scenario', models.TextField(help_text='Courtroom scenario for the game')),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Players'), ('ready', 'Ready to Start'), ('active', 'Game Active'), ('completed', 'Completed')], default='waiting', max_length=20)),
                ('player1_role', models.CharField(blank=True, choices=[('judge', 'Judge'), ('prosecutor', 'Prosecutor'), ('defense', 'Defense Attorney'), ('investigator', 'Investigator')], max_length=20, null=True)),
                ('player2_role', models.CharField(blank=True, choices=[('judge', 'Judge'), ('prosecutor', 'Prosecutor'), ('defense', 'Defense Attorney'), ('investigator', 'Investigator')], max_length=20, null=True)),
                ('player1_score', models.IntegerField(default=0)),
                ('player2_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to=settings.AUTH_USER_MODEL)),
                ('current_turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_turn_rooms', to=settings.AUTH_USER_MODEL)),
                ('player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mp_games_as_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mp_games_as_player2', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MultiplayerGameMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_type', models.CharField(help_text='Type of move (question, argument, decision, etc.)', max_length=50)),
                ('move_data', models.JSONField(help_text='Data for the move')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='games.multiplayergameroom')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
