# Generated by Django 6.0.1 on 2026-01-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_multiplayergameroom_multiplayergamemove'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='description_hy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='scenario_en',
            field=models.TextField(help_text='Game scenario/story', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='scenario_hy',
            field=models.TextField(help_text='Game scenario/story', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='scenario_ru',
            field=models.TextField(help_text='Game scenario/story', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='title_hy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gameanswer',
            name='answer_text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gameanswer',
            name='answer_text_hy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gameanswer',
            name='answer_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gameanswer',
            name='explanation_en',
            field=models.TextField(blank=True, help_text='Explanation shown after answering', null=True),
        ),
        migrations.AddField(
            model_name='gameanswer',
            name='explanation_hy',
            field=models.TextField(blank=True, help_text='Explanation shown after answering', null=True),
        ),
        migrations.AddField(
            model_name='gameanswer',
            name='explanation_ru',
            field=models.TextField(blank=True, help_text='Explanation shown after answering', null=True),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='question_text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='question_text_hy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='question_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gametype',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gametype',
            name='description_hy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gametype',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gametype',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gametype',
            name='name_hy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gametype',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
